vigilant {
  upstream-url = "http://127.0.0.1:1234"
  port = 9009

  upstream-connect-timeout = 10s
  upstream-write-timeout = 30s
  upstream-response-timeout = 5m
  upstream-connection-idle-timeout = 10s

  otlp-enabled = false
}